MySQL:
  ativar: false #false = SQLite, true = MySQL
  user: root
  pass: ''
  host: localhost:3306
  database: test

CashInicial: #Cash inicial ao entrar no servidor pela primeira vez.
  ativar: false #Caso queira ativar o cash inicial deixe true, caso não queira, deixe false.
  cash: 0.0 #Ignore caso a opção 'ativar' estiver false;

Formatter:
  ativar: true #Caso queira ativar formatador de cash deixe true, caso não queira, deixe false.
  suffixes:
    - '' #DEIXE UM ESPAÇO VÁZIO NA LISTA.
    - 'K' #K = Mil;
    - 'M' #M = Milhão;
    - 'B' #B = Bilhão;
    - 'T' #T = Trilhão;
    - 'Q' #Q = Quadrilhão;
    - 'QQ' #QQ = Quintilhão;
    - 'S' #S = Sextilhão;
    - 'SS' #SS = Septilhão;
    - 'O' #O = Octilhão;
    - 'N' #N = Nonilhão;
    - 'D' #D = Decilhão;